### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by Abacus-web** [ltkhang/sdn-ids-ddos-defense#12]
Hi sir,

please how to reproduce your result on live traffic with sdn controller and mininet.

**Comment by ltkhang** [comment]
> Hi sir,
> 
> please how to reproduce your result on live traffic with sdn controller and mininet.

Hi,

https://github.com/ltkhang/mininet-nat

This one helps open NAT for  mininet host talking to the outside network

https://github.com/ltkhang/ryu-controller

This one helps create controller for mininet

https://github.com/ltkhang/monitor-client

This one is for visualizing the result with web-base UI

My thesis is written in Vietnamese, you can translate  it with Google translate

https://github.com/ltkhang/ddos-detection-deeplearning/blob/master/DOC/thesis.pdf

The main parts are 4 (after 4.3 is for SDN), 5, and 6.

Best,

**Comment by Abacus-web** [comment]
thanks sir


> > Hi sir,
> > please how to reproduce your result on live traffic with sdn controller and mininet.
> 
> Hi,
> 
> https://github.com/ltkhang/mininet-nat
> 
> This one helps open NAT for mininet host talking to the outside network
> 
> https://github.com/ltkhang/ryu-controller
> 
> This one helps create controller for mininet
> 
> https://github.com/ltkhang/monitor-client
> 
> This one is for visualizing the result with web-base UI
> 
> My thesis is written in Vietnamese, you can translate it with Google translate
> 
> https://github.com/ltkhang/ddos-detection-deeplearning/blob/master/DOC/thesis.pdf
> 
> The main parts are 4 (after 4.3 is for SDN), 5, and 6.
> 
> Best,

Thanks sir
