### ISSUE TITLE
Performance Evaluation

### ISSUE THREAD

**Issue by Mambo1818** [ltkhang/sdn-ids-ddos-defense#2]
Mr Itkhang,
Is your model performing satisfactorily?? Have you tried it on live traffic flows?? what is the response?

**Comment by ltkhang** [comment]
> Mr Itkhang,
> Is your model performing satisfactorily?? Have you tried it on live traffic flows?? what is the response?

Hi, 

I'm gonna defense my undergrad thesis next week. I will publish the full code and guide soon. 

I have test with HOIC, LOIC UDP and Hulk in live traffic in a simulation SDN network and it preformed pretty good.

**Comment by ltkhang** [comment]
Here is the code to train model: https://github.com/ltkhang/ddos-detection-deeplearning
