### ISSUE TITLE
[Enhancement] integration with NFStream

### ISSUE THREAD

**Issue by aouinizied** [ltkhang/sdn-ids-ddos-defense#5]
Hi, 

I come up to this project and looks like it fits perfectely to a framework we designed for purpose. Do you think it is possible for you to test performance improvement using NFStream?

Github repo: https://github.com/nfstream/nfstream

Regards

**Comment by ltkhang** [comment]
Hi, thank you for your attention. Your framework is really cool. If you can convert the datasets I mentioned in my paper from raw packets (pcap) to your style (statistical one). I hope I can cooperate with you to produce new research for network intrusion detection using machine learning. The statistical data I used for my research was produced by the author.
